git rm     utils/goagent/Microsoft.VC90.CRT.manifest
git rm     utils/goagent/addto-startup.vbs
git rm     utils/goagent/certs/91.189.89.105.crt
git rm     utils/goagent/certs/91.189.89.105.key
git rm     utils/goagent/certs/addons.seleniumhq.org.crt
git rm     utils/goagent/certs/addons.seleniumhq.org.key
git rm     utils/goagent/certs/ajax.microsoft.com.crt
git rm     utils/goagent/certs/ajax.microsoft.com.key
git rm     utils/goagent/certs/apps.skype.com.crt
git rm     utils/goagent/certs/apps.skype.com.key
git rm     utils/goagent/certs/apps.skypeassets.com.crt
git rm     utils/goagent/certs/apps.skypeassets.com.key
git rm     utils/goagent/certs/armmf.adobe.com.crt
git rm     utils/goagent/certs/armmf.adobe.com.key
git rm     utils/goagent/certs/daw.apple.com.crt
git rm     utils/goagent/certs/daw.apple.com.key
git rm     utils/goagent/certs/developer.apple.com.crt
git rm     utils/goagent/certs/developer.apple.com.key
git rm     utils/goagent/certs/devimages.apple.com.edgekey.net.crt
git rm     utils/goagent/certs/devimages.apple.com.edgekey.net.key
git rm     utils/goagent/certs/drh.img.digitalriver.com.crt
git rm     utils/goagent/certs/drh.img.digitalriver.com.key
git rm     utils/goagent/certs/i.w55c.net.crt
git rm     utils/goagent/certs/i.w55c.net.key
git rm     utils/goagent/certs/login.skype.com.crt
git rm     utils/goagent/certs/login.skype.com.key
git rm     utils/goagent/certs/m.webtrends.com.crt
git rm     utils/goagent/certs/m.webtrends.com.key
git rm     utils/goagent/certs/mpsnare.iesnare.com.crt
git rm     utils/goagent/certs/mpsnare.iesnare.com.key
git rm     utils/goagent/certs/nexus.ensighten.com.crt
git rm     utils/goagent/certs/nexus.ensighten.com.key
git rm     utils/goagent/certs/p01-contacts.icloud.com.crt
git rm     utils/goagent/certs/p01-contacts.icloud.com.key
git rm     utils/goagent/certs/p24-buy.itunes.apple.com.crt
git rm     utils/goagent/certs/p24-buy.itunes.apple.com.key
git rm     utils/goagent/certs/pagead2.googleadservices.com.crt
git rm     utils/goagent/certs/pagead2.googleadservices.com.key
git rm     utils/goagent/certs/reg.163.com.crt
git rm     utils/goagent/certs/reg.163.com.key
git rm     utils/goagent/certs/s3-s.licdn.com.crt
git rm     utils/goagent/certs/s3-s.licdn.com.key
git rm     utils/goagent/certs/s4-s.licdn.com.crt
git rm     utils/goagent/certs/s4-s.licdn.com.key
git rm     utils/goagent/certs/se.itunes.apple.com.crt
git rm     utils/goagent/certs/se.itunes.apple.com.key
git rm     utils/goagent/certs/secure.img-cdn.mediaplex.com.crt
git rm     utils/goagent/certs/secure.img-cdn.mediaplex.com.key
git rm     utils/goagent/certs/secure.skypeassets.com.crt
git rm     utils/goagent/certs/secure.skypeassets.com.key
git rm     utils/goagent/certs/ssl.apple.com.crt
git rm     utils/goagent/certs/ssl.apple.com.key
git rm     utils/goagent/certs/versioncheck-bg.addons.mozilla.org.crt
git rm     utils/goagent/certs/versioncheck-bg.addons.mozilla.org.key
git rm     utils/goagent/certs/www.163.com.crt
git rm     utils/goagent/certs/www.163.com.key
git rm     utils/goagent/certs/www.gmail.com.crt
